//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateOrder
    {
        public long idStateOrder { get; set; }
        public string nameState { get; set; }
    }
}
